#!/usr/bin/env bash

source etc/banner
# Banner Add
echo -e "executing: ${LIGHTGREEN}OBBFIFA${NOCOLOR}"
echo "-----------------------"

if [[ -d "output" ]]
  then
    echo ""
  else
    echo ""
    mkdir output
fi

unpacking () {
  qemu-i386 $PREFIX/share/quickbms/quickbms -Q etc/ea_big4.bms $opt output
}

repacking () {
  qemu-i386 $PREFIX/share/quickbms/quickbms -w -r -r etc/ea_big4.bms $opt output
}

function unpack {
prompt="Please select a file to unpack:"
options=( $(find *.obb) )

PS3="$prompt "
select opt in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "You picked $opt which is file $REPLY"
         unpacking
        break

    else
        echo "Invalid option. Try another one."
    fi
done
}

function repack {
prompt="Please select a file to repack:"
options=( $(find *.obb) )

PS3="$prompt "
select opt in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "You picked $opt which is file $REPLY"
         repacking
        break
    else
        echo "Invalid option. Try another one."
    fi
done
}

PS3='Please enter your choice: '
options=("Unpack" "Repack" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Unpack")
            unpack
            break
            ;;
        "Repack")
            repack
            
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done 
